### Problems

#### Problem B1 {.unnumbered}

Consider the matrix $$
\boldsymbol A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}.
$$

a)  Determine $\boldsymbol A'$. Is $\boldsymbol A$ symmetric?
b)  Is $\boldsymbol A$ idempotent?
c)  Compute the determinant and the rank. Is $\boldsymbol A$
    nonsingular?
d)  Compute the inverse.
e)  Compute the trace.

#### Problem B2 {.unnumbered}

a)  Let $\boldsymbol A \boldsymbol B = \boldsymbol C$, where $$
    \boldsymbol A = \begin{pmatrix} 1 & 0 \\ 2 & 2 \end{pmatrix}, \quad
    \boldsymbol C = \begin{pmatrix} 1 & 3 \\ 2 & 5 \end{pmatrix}.
    $$ Compute $\boldsymbol B$.
b)  $\boldsymbol \delta$ and $\boldsymbol \gamma$ are $c \times 1$
    vectors, $\boldsymbol X$ is a $d \times c$ matrix, and
    $\boldsymbol Y$ is a $c \times d$ matrix. Determine the orders of
    $\boldsymbol X \boldsymbol Y$, $\boldsymbol Y \boldsymbol X$,
    $\boldsymbol \gamma' \boldsymbol \gamma$,
    $\boldsymbol \gamma \boldsymbol \gamma'$, and
    $\boldsymbol \delta' \boldsymbol Y \boldsymbol X \boldsymbol \gamma$.
    Under which conditions do the expressions $\boldsymbol Y^{-1}$ and
    $\boldsymbol \delta' \boldsymbol Y \boldsymbol X + \boldsymbol \gamma' \boldsymbol \gamma$
    exist?
c)  Compute $\mathop{\mathrm{tr}}(\lambda \boldsymbol R' \boldsymbol R)$ for
    $\lambda \in \mathbb R$ and $$
    \boldsymbol R = \begin{pmatrix} \frac{1}{4} & \frac{\sqrt 3}{4} \\ \frac{\sqrt 3}{4} & \frac{3}{4} \end{pmatrix}.
    $$

#### Problem B3 {.unnumbered}

Let $\boldsymbol A$ be nonsingular. Simplify the expression $$
  \bigg( \frac{1}{\sqrt 2} \boldsymbol A^{-1} \bigg( \frac{1}{\sqrt 2} \boldsymbol A'' + \frac{\sqrt 2}{2} \boldsymbol A \bigg) \bigg).
$$

#### Problem B4 {.unnumbered}

Consider the $n \times k$ matrix $\boldsymbol X$ with
$\mathop{\mathrm{rank}}(\boldsymbol X) = k$. Moreover, let
$\boldsymbol P = \boldsymbol X (\boldsymbol X' \boldsymbol X)^{-1} \boldsymbol X'$,
and let $\boldsymbol M = \boldsymbol I_n - \boldsymbol P$

a)  Determine the order of the following matrices: $\boldsymbol I_n$,
    $\boldsymbol X' \boldsymbol X$, $\boldsymbol P$, $\boldsymbol M$
b)  Which matrices from a) are symmetric?
c)  Which matrices from a) are idempotent?
d)  Compute the trace of $\boldsymbol I_n$ and $\boldsymbol P$.

#### Problem B5 {.unnumbered}

Let $\boldsymbol X$ be a $n \times k$ matrix. Show that
$\boldsymbol X' \boldsymbol X$ is positive semi-definite. Under which
condition is $\boldsymbol X' \boldsymbol X$ positive definite?

#### Problem B6 {.unnumbered}

Let $\boldsymbol y \in \mathbb R^n$, $\boldsymbol X$ be a $n \times k$
matrix, and $\boldsymbol \beta \in \mathbb R^k$. Compute the derivatives
$$
  \frac{\partial f(\boldsymbol \beta)}{\partial \boldsymbol \beta}, \quad 
  \frac{\partial^2 f(\boldsymbol \beta)}{\partial \boldsymbol \beta \boldsymbol \beta'},
$$ for the function
$f(\boldsymbol \beta) = (\boldsymbol y - \boldsymbol X \boldsymbol \beta)'(\boldsymbol y - \boldsymbol X \boldsymbol \beta)$.

### Solutions
